# cant use mem_limit in a 3.x docker-compose file in non swarm mode
# see https://github.com/docker/compose/issues/4513
version: "2.4"

services:
  whoogle-search:
    image: milachevalier/search
    container_name: search
    restart: on-failure:5
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    # user debian-tor from tor package
    user: '102'
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /config/:size=10M,uid=102,gid=102,mode=1700
      - /var/lib/tor/:size=10M,uid=102,gid=102,mode=1700
      - /run/tor/:size=1M,uid=102,gid=102,mode=1700
    environment:  
      # Basic auth configuration, uncomment to enable
      #- WHOOGLE_USER=<auth username>
      #- WHOOGLE_PASS=<auth password>
      # Proxy configuration, uncomment to enable
      #- WHOOGLE_PROXY_USER=<proxy username>
      #- WHOOGLE_PROXY_PASS=<proxy password>
      #- WHOOGLE_PROXY_TYPE=<proxy type (http|socks4|socks5)
      #- WHOOGLE_PROXY_LOC=<proxy host/ip>
      # Site alternative configurations, uncomment to enable
      # Note: If not set, the feature will still be available
      # with default values. 
      #- WHOOGLE_ALT_TW=nitter.net
      #- WHOOGLE_ALT_YT=invidious.snopyta.org
      #- WHOOGLE_ALT_IG=bibliogram.art/u
      #- WHOOGLE_ALT_RD=libredd.it
      WHOOGLE_CONFIG_STYLE=":root{--whoogle-logo:#685e79;--whoogle-page-bg:#ffffff;--whoogle-element-bg:#4285f4;--whoogle-text:#000000;--whoogle-contrast-text:#ffffff;--whoogle-secondary-text:#70757a;--whoogle-result-bg:#ffffff;--whoogle-result-title:#1967d2;--whoogle-result-url:#0d652d;--whoogle-result-visited:#4b11a8}#config-collapsible{display:none!important}html{font-family:arial,sans-serif!important}.BnJWBc,.logo-container,.logo-div,.mobile-logo{display:none!important}@media all and (min-width:750px){body{margin:0 150px!important}.x54gtf{background-color:#fff!important;margin:-10px 16px!important}.ZINbbc{box-shadow:none!important;margin-bottom:0!important}.vvjwJb{font-size:19px!important;line-height:1.3em!important}.search-div{margin-top:20px!important}:root{--whoogle-result-title:#1a0dab;--whoogle-result-url:#202124;--whoogle-result-visited:#609}}"
      # Load environment variables from whoogle.env
      #- WHOOGLE_DOTENV=1
    ports:
      - 5000:5000
    restart: unless-stopped
